# -*- coding: utf-8 -*-
"""pascal_voc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iNH4VXNmwPdExEXZGqImyL39ydPkB2UK

# Pascal VOC 2012 — EDA & Data Preprocessing

| Property | Value |
|---|---|
| Dataset | PASCAL Visual Object Classes 2012 |
| Task | Detection / Segmentation / Classification |
| Classes | 20 object categories |
| Total Images | 11,540 (trainval) |
| Format | XML annotations |

## Step 0 — Setup & Imports
"""

import os, warnings
import xml.etree.ElementTree as ET
from pathlib import Path
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image
from tqdm import tqdm

# White background style
plt.rcParams.update({
    'figure.facecolor':  'white',
    'axes.facecolor':    'white',
    'axes.edgecolor':    '#cccccc',
    'axes.spines.top':   False,
    'axes.spines.right': False,
    'text.color':        '#222222',
    'axes.labelcolor':   '#444444',
    'xtick.color':       '#555555',
    'ytick.color':       '#555555',
    'grid.color':        '#eeeeee',
    'grid.linewidth':    0.8,
    'font.family':       'sans-serif',
    'font.size':         11,
    'axes.titlesize':    13,
    'axes.labelsize':    11,
    'figure.dpi':        110,
})

PALETTE = [
    '#4C72B0','#DD8452','#55A868','#C44E52','#8172B3',
    '#937860','#DA8BC3','#8C8C8C','#CCB974','#64B5CD',
    '#4C72B0','#DD8452','#55A868','#C44E52','#8172B3',
    '#937860','#DA8BC3','#8C8C8C','#CCB974','#64B5CD'
]

VOC_CLASSES = [
    'aeroplane','bicycle','bird','boat','bottle','bus','car','cat',
    'chair','cow','diningtable','dog','horse','motorbike','person',
    'pottedplant','sheep','sofa','train','tvmonitor'
]
CLASS_TO_IDX = {c: i for i, c in enumerate(VOC_CLASSES)}

print(f'Imports OK | {len(VOC_CLASSES)} classes')

"""## Step 1 — Dataset Loading
### 1.1 Download / Mount VOC 2012
"""

# Option A: Kaggle
!pip install kaggle -q
!kaggle datasets download -d huanghanchina/pascal-voc-2012
!unzip pascal-voc-2012.zip -d ./VOCdevkit

VOC_ROOT = Path('./VOCdevkit/VOC2012')   # <- sua duong dan
IMG_DIR  = VOC_ROOT / 'JPEGImages'
ANN_DIR  = VOC_ROOT / 'Annotations'
SEG_DIR  = VOC_ROOT / 'SegmentationClass'
SETS_DIR = VOC_ROOT / 'ImageSets' / 'Main'

if VOC_ROOT.exists():
    imgs = list(IMG_DIR.glob('*.jpg'))
    anns = list(ANN_DIR.glob('*.xml'))
    print(f'VOC_ROOT : {VOC_ROOT}')
    print(f'Images   : {len(imgs):,}')
    print(f'Annots   : {len(anns):,}')
else:
    print('VOC_ROOT khong ton tai -> chay simulate mode.')

"""### 1.2 Parse XML Annotations -> DataFrame"""

def parse_voc_xml(xml_path):
    tree = ET.parse(xml_path)
    root = tree.getroot()
    img_id = root.findtext('filename').replace('.jpg','')
    W = int(root.find('size/width').text)
    H = int(root.find('size/height').text)
    rows = []
    for obj in root.findall('object'):
        name      = obj.findtext('name')
        difficult = int(obj.findtext('difficult') or 0)
        truncated = int(obj.findtext('truncated') or 0)
        occluded  = int(obj.findtext('occluded')  or 0) if obj.find('occluded') else 0
        bb   = obj.find('bndbox')
        xmin = float(bb.findtext('xmin'))
        ymin = float(bb.findtext('ymin'))
        xmax = float(bb.findtext('xmax'))
        ymax = float(bb.findtext('ymax'))
        bw, bh = xmax-xmin, ymax-ymin
        rows.append({
            'img_id':img_id,'img_w':W,'img_h':H,
            'class':name,'class_idx':CLASS_TO_IDX.get(name,-1),
            'difficult':difficult,'truncated':truncated,'occluded':occluded,
            'xmin':xmin,'ymin':ymin,'xmax':xmax,'ymax':ymax,
            'bw':bw,'bh':bh,'area':bw*bh,
            'aspect_ratio':bw/(bh+1e-6),
            'cx_norm':(xmin+xmax)/2/W,'cy_norm':(ymin+ymax)/2/H,
            'rel_area':bw*bh/(W*H),
        })
    return rows


if ANN_DIR.exists():
    records = []
    for xf in tqdm(sorted(ANN_DIR.glob('*.xml')), desc='Parsing XMLs'):
        try: records.extend(parse_voc_xml(xf))
        except: pass
    df = pd.DataFrame(records)
else:
    # Simulate
    np.random.seed(42)
    trainval_counts = {
        'aeroplane':670,'bicycle':552,'bird':1165,'boat':712,'bottle':1100,
        'bus':421,'car':1644,'cat':1209,'chair':1671,'cow':431,
        'diningtable':537,'dog':1508,'horse':644,'motorbike':575,'person':10982,
        'pottedplant':844,'sheep':564,'sofa':425,'train':481,'tvmonitor':645
    }
    mean_wh = {
        'aeroplane':(248,120),'bicycle':(158,192),'bird':(110,118),
        'boat':(152,98),'bottle':(62,138),'bus':(262,192),'car':(188,122),
        'cat':(218,228),'chair':(128,168),'cow':(198,162),
        'diningtable':(268,218),'dog':(198,198),'horse':(228,198),
        'motorbike':(178,178),'person':(88,188),'pottedplant':(108,148),
        'sheep':(138,128),'sofa':(278,188),'train':(298,168),'tvmonitor':(162,148)
    }
    rows, img_id = [], 0
    for cls, cnt in trainval_counts.items():
        mw, mh = mean_wh[cls]
        for _ in range(cnt):
            iw = np.random.choice([500,375])
            ih = 375 if iw==500 else 500
            bw = max(20, int(np.random.normal(mw, mw*0.25)))
            bh = max(20, int(np.random.normal(mh, mh*0.25)))
            bw, bh = min(bw,iw-1), min(bh,ih-1)
            xmin = np.random.randint(0, max(1,iw-bw))
            ymin = np.random.randint(0, max(1,ih-bh))
            xmax, ymax = xmin+bw, ymin+bh
            rows.append({
                'img_id':f'{img_id:06d}','img_w':iw,'img_h':ih,
                'class':cls,'class_idx':CLASS_TO_IDX[cls],
                'difficult':int(np.random.rand()<0.05),
                'truncated':int(np.random.rand()<0.15),
                'occluded': int(np.random.rand()<0.20),
                'xmin':xmin,'ymin':ymin,'xmax':xmax,'ymax':ymax,
                'bw':bw,'bh':bh,'area':bw*bh,
                'aspect_ratio':bw/(bh+1e-6),
                'cx_norm':(xmin+xmax)/2/iw,'cy_norm':(ymin+ymax)/2/ih,
                'rel_area':bw*bh/(iw*ih),
            })
            img_id += 1
    df = pd.DataFrame(rows)

df['split'] = np.random.choice(['train','val'], size=len(df), p=[0.6,0.4])
print(f'DataFrame shape: {df.shape}')
df.head(3)

"""## Step 2 — Dataset Overview"""

total_imgs  = df['img_id'].nunique()
total_objs  = len(df)
obj_per_img = df.groupby('img_id').size()

summary = pd.DataFrame({
    'Metric': [
        'Total images','Total bounding boxes','Unique classes',
        'Avg objects / image','Max objects / image',
        'Difficult (%)','Truncated (%)','Occluded (%)'
    ],
    'Value': [
        f'{total_imgs:,}', f'{total_objs:,}', str(df["class"].nunique()),
        f'{obj_per_img.mean():.2f}', str(obj_per_img.max()),
        f'{df["difficult"].mean()*100:.1f}%',
        f'{df["truncated"].mean()*100:.1f}%',
        f'{df["occluded"].mean()*100:.1f}%',
    ]
})
print(summary.to_string(index=False))

"""## Step 3 — Class Distribution
### 3.1 Objects per Class
"""

cls_counts = df['class'].value_counts().sort_values(ascending=True)

fig, ax = plt.subplots(figsize=(10, 7))

# Set a single color here
single_color = 'steelblue'

# Pass the single color to the 'color' argument
bars = ax.barh(cls_counts.index, cls_counts.values, color=single_color, height=0.65, edgecolor='none')

for bar, val in zip(bars, cls_counts.values):
    ax.text(val + 80, bar.get_y() + bar.get_height()/2,
            f'{val:,}', va='center', fontsize=9, color='#444')

ax.axvline(cls_counts.mean(), color='#e74c3c', ls='--', lw=1.5,
           label=f'Mean = {cls_counts.mean():.0f}')

ax.set_xlabel('Number of Objects')
ax.set_title('Objects per Class (trainval)')
ax.set_xlim(0, cls_counts.max() * 1.15)
ax.legend()
ax.grid(axis='x', linestyle=':', alpha=0.7)
plt.tight_layout()
plt.savefig('fig_class_counts.png', dpi=120, bbox_inches='tight')
plt.show()

"""### 3.2 Train / Val Split per Class"""

split_df = df.groupby(['class','split']).size().unstack(fill_value=0)
split_df = split_df.loc[cls_counts.sort_values(ascending=False).index]
x = np.arange(len(split_df))
w = 0.4

fig, ax = plt.subplots(figsize=(13, 5))
ax.bar(x - w/2, split_df.get('train',0), w, label='Train', color='#4C72B0', alpha=0.85)
ax.bar(x + w/2, split_df.get('val',  0), w, label='Val',   color='#DD8452', alpha=0.85)
ax.set_xticks(x)
ax.set_xticklabels(split_df.index, rotation=40, ha='right')
ax.set_ylabel('Number of Objects')
ax.set_title('Train / Val Split per Class')
ax.legend(); ax.grid(axis='y')
plt.tight_layout()
plt.savefig('fig_train_val_split.png', dpi=120, bbox_inches='tight')
plt.show()

"""### 3.3 Class Imbalance — Count + Cumulative Coverage"""

sorted_counts = cls_counts.sort_values(ascending=False)
cumsum = sorted_counts.cumsum() / sorted_counts.sum() * 100

fig, ax = plt.subplots(figsize=(13, 5))
ax.bar(range(len(sorted_counts)), sorted_counts.values,
       color=[PALETTE[VOC_CLASSES.index(c)] for c in sorted_counts.index],
       edgecolor='none', alpha=0.85)
ax2 = ax.twinx()
ax2.plot(range(len(sorted_counts)), cumsum.values,
         color='#e74c3c', lw=2, marker='o', markersize=4, label='Cumulative %')
ax2.axhline(80, color='gray', ls=':', lw=1.2, label='80% threshold')
ax2.set_ylabel('Cumulative Coverage (%)', color='#e74c3c')
ax2.set_ylim(0, 110)
ax2.legend(loc='lower right')
ax.set_xticks(range(len(sorted_counts)))
ax.set_xticklabels(sorted_counts.index, rotation=40, ha='right')
ax.set_ylabel('Object Count')
ax.set_title('Class Imbalance — Count + Cumulative Coverage')
ax.grid(axis='y')
plt.tight_layout()
plt.savefig('fig_imbalance_cumulative.png', dpi=120, bbox_inches='tight')
plt.show()

print(f"person chiem {sorted_counts['person']/sorted_counts.sum()*100:.1f}% tong objects")
print(f"Imbalance ratio (max/min): {sorted_counts.max()/sorted_counts.min():.0f}x")

"""## Step 4 — Bounding Box Analysis
### 4.1 BBox Width Distribution
"""

fig, ax = plt.subplots(figsize=(10, 4))
ax.hist(df['bw'], bins=80, color='#4C72B0', alpha=0.8, edgecolor='none')
ax.axvline(df['bw'].mean(),   color='#e74c3c', lw=2, label=f'Mean   = {df["bw"].mean():.0f} px')
ax.axvline(df['bw'].median(), color='#27ae60', lw=2, ls='--', label=f'Median = {df["bw"].median():.0f} px')
ax.set_xlabel('BBox Width (px)')
ax.set_ylabel('Count')
ax.set_title('BBox Width Distribution')
ax.legend(); ax.grid()
plt.tight_layout()
plt.savefig('fig_bbox_width.png', dpi=120, bbox_inches='tight')
plt.show()

"""### 4.2 BBox Height Distribution"""

fig, ax = plt.subplots(figsize=(10, 4))
ax.hist(df['bh'], bins=80, color='#55A868', alpha=0.8, edgecolor='none')
ax.axvline(df['bh'].mean(),   color='#e74c3c', lw=2, label=f'Mean   = {df["bh"].mean():.0f} px')
ax.axvline(df['bh'].median(), color='#4C72B0', lw=2, ls='--', label=f'Median = {df["bh"].median():.0f} px')
ax.set_xlabel('BBox Height (px)')
ax.set_ylabel('Count')
ax.set_title('BBox Height Distribution')
ax.legend(); ax.grid()
plt.tight_layout()
plt.savefig('fig_bbox_height.png', dpi=120, bbox_inches='tight')
plt.show()

"""### 4.3 Aspect Ratio Distribution"""

ar = df['aspect_ratio'].clip(0, 5)

fig, ax = plt.subplots(figsize=(10, 4))
ax.hist(ar, bins=80, color='#DD8452', alpha=0.8, edgecolor='none')
ax.axvline(1.0, color='#444', lw=1.5, ls=':', label='Square (AR=1)')
ax.axvline(ar.mean(), color='#e74c3c', lw=2, label=f'Mean = {ar.mean():.2f}')
ax.set_xlabel('Aspect Ratio  W / H')
ax.set_ylabel('Count')
ax.set_title('BBox Aspect Ratio Distribution')
ax.legend(); ax.grid()
plt.tight_layout()
plt.savefig('fig_aspect_ratio.png', dpi=120, bbox_inches='tight')
plt.show()

"""### 4.4 Median Relative BBox Area per Class"""

# Calculate median relative area
area_by_cls = df.groupby('class')['rel_area'].median().sort_values(ascending=True)

fig, ax = plt.subplots(figsize=(10, 7))

# Set a single uniform color
single_color = '#2ecc71'

# Plot bars with a single color
ax.barh(area_by_cls.index, area_by_cls.values * 100, color=single_color, height=0.65, edgecolor='none')

ax.set_xlabel('Median Relative Area (% of image)')
ax.set_title('Median BBox Relative Area per Class')
ax.grid(axis='x', linestyle='--', alpha=0.6)

# Data labels
for i, (cls, val) in enumerate(area_by_cls.items()):
    ax.text(val*100 + 0.2, i, f'{val*100:.1f}%', va='center', fontsize=8.5, color='#333')

plt.tight_layout()
plt.savefig('fig_bbox_area_per_class.png', dpi=120, bbox_inches='tight')
plt.show()

"""### 4.5 BBox Center Heatmap"""

h, xe, ye = np.histogram2d(df['cx_norm'], df['cy_norm'], bins=40, range=[[0,1],[0,1]])

fig, ax = plt.subplots(figsize=(6, 5))
im = ax.imshow(h.T, origin='lower', cmap='YlOrRd', aspect='auto', extent=[0,1,0,1])
plt.colorbar(im, ax=ax, label='Count')
ax.set_xlabel('cx (normalised)')
ax.set_ylabel('cy (normalised)')
ax.set_title('BBox Center Distribution Heatmap')
plt.tight_layout()
plt.savefig('fig_center_heatmap.png', dpi=120, bbox_inches='tight')
plt.show()

"""### 4.6 Objects per Image"""

obj_per_img = df.groupby('img_id').size()
counts = obj_per_img.value_counts().sort_index()

fig, ax = plt.subplots(figsize=(10, 4))
ax.bar(counts.index, counts.values, color='#8172B3', alpha=0.85, edgecolor='none')
ax.axvline(obj_per_img.mean(), color='#e74c3c', lw=2, label=f'Mean = {obj_per_img.mean():.1f}')
ax.set_xlabel('Objects per Image')
ax.set_ylabel('Number of Images')
ax.set_title('Objects per Image Distribution')
ax.legend(); ax.grid(axis='y')
plt.tight_layout()
plt.savefig('fig_objs_per_image.png', dpi=120, bbox_inches='tight')
plt.show()

"""## Step 5 — Image Properties
### 5.1 Resolution Distribution
"""

img_df = df.drop_duplicates('img_id')[['img_id','img_w','img_h']].copy()
img_df['resolution_kpx'] = img_df['img_w'] * img_df['img_h'] / 1000

fig, ax = plt.subplots(figsize=(10, 4))
ax.hist(img_df['resolution_kpx'], bins=50, color='#64B5CD', alpha=0.85, edgecolor='none')
ax.axvline(img_df['resolution_kpx'].mean(), color='#e74c3c', lw=2,
           label=f'Mean = {img_df["resolution_kpx"].mean():.0f} Kpx')
ax.set_xlabel('Resolution (Kpx)')
ax.set_ylabel('Count')
ax.set_title('Image Resolution Distribution')
ax.legend(); ax.grid()
plt.tight_layout()
plt.savefig('fig_resolution.png', dpi=120, bbox_inches='tight')
plt.show()

print('Top 5 most common resolutions:')
print(img_df.groupby(['img_w','img_h']).size().sort_values(ascending=False).head(5).to_string())

"""### 5.2 Width vs Height Scatter"""

img_df['orientation'] = (img_df['img_w']/img_df['img_h']).apply(
    lambda r: 'Landscape' if r>1.05 else ('Portrait' if r<0.95 else 'Square'))

color_map = {'Landscape':'#4C72B0','Portrait':'#DD8452','Square':'#55A868'}

fig, ax = plt.subplots(figsize=(7, 6))
for ori, grp in img_df.groupby('orientation'):
    ax.scatter(grp['img_w'], grp['img_h'], alpha=0.35, s=12,
               color=color_map[ori], label=f'{ori} ({len(grp):,})')
ax.set_xlabel('Image Width (px)')
ax.set_ylabel('Image Height (px)')
ax.set_title('Image Width vs Height')
ax.legend(); ax.grid()
plt.tight_layout()
plt.savefig('fig_wh_scatter.png', dpi=120, bbox_inches='tight')
plt.show()

"""## Step 6 — Pixel / Color Analysis
### 6.1 Per-Channel Histograms
"""

if IMG_DIR.exists():
    sample_paths = list(IMG_DIR.glob('*.jpg'))[:500]
    ch_vals = {'R':[],'G':[],'B':[]}
    for p in tqdm(sample_paths, desc='Sampling pixels'):
        img = np.array(Image.open(p).convert('RGB'), dtype=np.float32)
        for i, ch in enumerate(['R','G','B']):
            ch_vals[ch].extend(img[:,:,i].flatten()[::50].tolist())
else:
    ch_params = {'R':(123.7,58.1),'G':(117.2,55.8),'B':(103.5,57.3)}
    ch_vals   = {ch: np.random.normal(mu,sg,300000).clip(0,255).tolist()
                 for ch,(mu,sg) in ch_params.items()}

ch_colors = {'R':'#C44E52','G':'#55A868','B':'#4C72B0'}
for ch in ['R','G','B']:
    vals = np.array(ch_vals[ch])
    fig, ax = plt.subplots(figsize=(9, 4))
    ax.hist(vals, bins=100, color=ch_colors[ch], alpha=0.75, edgecolor='none', density=True)
    ax.axvline(vals.mean(), color='#222', lw=2, label=f'mean = {vals.mean():.1f}')
    ax.set_xlabel('Pixel value (0-255)')
    ax.set_ylabel('Density')
    ax.set_title(f'{ch} Channel Distribution')
    ax.legend(); ax.grid()
    plt.tight_layout()
    plt.savefig(f'fig_channel_{ch}.png', dpi=120, bbox_inches='tight')
    plt.show()

print('ImageNet normalisation (standard for VOC):')
print('  mean = (0.485, 0.456, 0.406)')
print('  std  = (0.229, 0.224, 0.225)')

"""## Step 7 — Co-occurrence Analysis
### 7.1 Raw Co-occurrence Count
"""

co_matrix = np.zeros((20,20), dtype=int)
for _, grp in df.groupby('img_id'):
    idxs = [CLASS_TO_IDX[c] for c in set(grp['class']) if c in CLASS_TO_IDX]
    for i in idxs:
        for j in idxs:
            co_matrix[i,j] += 1

fig, ax = plt.subplots(figsize=(10, 8))
im = ax.imshow(co_matrix, cmap='Blues', aspect='auto')
plt.colorbar(im, ax=ax, fraction=0.03)
ax.set_xticks(range(20)); ax.set_yticks(range(20))
ax.set_xticklabels(VOC_CLASSES, rotation=45, ha='right', fontsize=8)
ax.set_yticklabels(VOC_CLASSES, fontsize=8)
ax.set_title('Class Co-occurrence Count')
plt.tight_layout()
plt.savefig('fig_cooccurrence_count.png', dpi=120, bbox_inches='tight')
plt.show()

"""### 7.2 Conditional Probability P(j | i)"""

diag    = np.diag(co_matrix).astype(float)
co_prob = co_matrix / (diag[:,None] + 1e-6)
np.fill_diagonal(co_prob, 0)

fig, ax = plt.subplots(figsize=(10, 8))
im2 = ax.imshow(co_prob, cmap='Oranges', aspect='auto', vmin=0, vmax=0.5)
plt.colorbar(im2, ax=ax, fraction=0.03, label='P(col | row)')
ax.set_xticks(range(20)); ax.set_yticks(range(20))
ax.set_xticklabels(VOC_CLASSES, rotation=45, ha='right', fontsize=8)
ax.set_yticklabels(VOC_CLASSES, fontsize=8)
ax.set_title('Conditional Co-occurrence  P(j | i)')
plt.tight_layout()
plt.savefig('fig_cooccurrence_prob.png', dpi=120, bbox_inches='tight')
plt.show()

pairs = [(VOC_CLASSES[i],VOC_CLASSES[j],co_prob[i,j]+co_prob[j,i])
         for i in range(20) for j in range(i+1,20)]
pairs.sort(key=lambda x:-x[2])
print('Top 5 co-occurring pairs:')
for a,b,p in pairs[:5]:
    print(f'  {a:<15} <-> {b:<15}  score={p:.3f}')

"""---

## Preprocessing Overview

Dựa trên kết quả EDA, pipeline tiền xử lý gồm các bước chính sau:

| Bước | Mô tả | Lý do |
|---|---|---|
| **1. Cleaning** | Loại bỏ `difficult=1`, clip bbox vượt biên ảnh, bỏ bbox degenerate (w≤0, h≤0) | ~5% objects bị đánh dấu difficult; một số bbox lệch biên do annotation thủ công |
| **2. Resize** | Đưa về kích thước cố định (512×512, 640×640, …) tùy model | Ảnh VOC có nhiều kích thước khác nhau (500×375, 375×500, …) |
| **3. Normalize** | Chia 255 → `[0,1]`, sau đó chuẩn hóa theo ImageNet mean/std | Pretrained backbone được train trên ImageNet với chuẩn hóa này |
| **4. Augmentation (train)** | Flip ngang, ColorJitter, RandomResizedCrop, RandomErasing, Mosaic, MixUp | Dataset nhỏ (~11K ảnh), tăng đa dạng giúp model generalize tốt hơn |
| **5. Class weights** | Tính trọng số nghịch đảo tần suất cho loss function | `person` chiếm ~41% → mất cân bằng nghiêm trọng (ratio ~20x) |

> **Note:** Augmentation chỉ áp dụng cho **train set**. Val/test set chỉ resize + normalize, không augment.

## Step 8 — Preprocessing Pipeline
### 8.1 Cleaning — Filter & Validate
"""

df_clean = df[df['difficult'] == 0].copy()
print(f'Removed difficult : {len(df)-len(df_clean):,} ({(len(df)-len(df_clean))/len(df)*100:.1f}%)')

mask_bad = (
    (df_clean['xmin'] >= df_clean['xmax']) |
    (df_clean['ymin'] >= df_clean['ymax']) |
    (df_clean['bw'] <= 0) | (df_clean['bh'] <= 0) |
    (df_clean['xmin'] < 0) | (df_clean['ymin'] < 0)
)
print(f'Invalid bboxes    : {mask_bad.sum():,}')
df_clean = df_clean[~mask_bad]

df_clean['xmin'] = df_clean['xmin'].clip(lower=0)
df_clean['ymin'] = df_clean['ymin'].clip(lower=0)
df_clean['xmax'] = df_clean[['xmax','img_w']].min(axis=1)
df_clean['ymax'] = df_clean[['ymax','img_h']].min(axis=1)

print(f'Final clean records: {len(df_clean):,}')
df_clean.head(3)

"""### 8.2 Transform Pipelines"""

import torchvision.transforms as T

IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD  = [0.229, 0.224, 0.225]

# Val / Test
val_transform = T.Compose([
    T.Resize((512, 512)),
    T.ToTensor(),
    T.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
])

# Train
train_transform = T.Compose([
    T.RandomHorizontalFlip(p=0.5),
    T.ColorJitter(brightness=0.3, contrast=0.3, saturation=0.3, hue=0.1),
    T.RandomGrayscale(p=0.05),
    T.RandomResizedCrop(size=(512,512), scale=(0.5,1.0), ratio=(0.75,1.33)),
    T.ToTensor(),
    T.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
    T.RandomErasing(p=0.1, scale=(0.02,0.15)),
])

print('Val transform:')
print(val_transform)
print('\nTrain transform:')
print(train_transform)

"""### 8.3 Augmentation — Baseline vs Val"""

import torch

def unnorm(tensor):
    t = tensor.clone()
    for c,m,s in zip(range(3),IMAGENET_MEAN,IMAGENET_STD):
        t[c] = t[c]*s + m
    return t.permute(1,2,0).numpy().clip(0,1)

if IMG_DIR.exists():
    orig = Image.open(list(IMG_DIR.glob('*.jpg'))[42]).convert('RGB')
else:
    arr = np.random.randint(80,200,(375,500,3),dtype=np.uint8)
    arr[80:220,120:320,0] = 210; arr[80:220,120:320,1] = 100
    orig = Image.fromarray(arr)

fig, axes = plt.subplots(1, 2, figsize=(10, 4))
axes[0].imshow(orig); axes[0].set_title('Original'); axes[0].axis('off')
axes[1].imshow(unnorm(val_transform(orig)))
axes[1].set_title('Val transform (Resize 512 + Normalize)'); axes[1].axis('off')
plt.suptitle('Baseline Preprocessing', fontsize=12)
plt.tight_layout()
plt.savefig('fig_aug_baseline.png', dpi=120, bbox_inches='tight')
plt.show()

"""### 8.4 Augmentation — 8 Random Train Samples"""

fig, axes = plt.subplots(2, 4, figsize=(14, 7))
for i, ax in enumerate(axes.flat):
    ax.imshow(unnorm(train_transform(orig)))
    ax.set_title(f'Aug #{i+1}', fontsize=9)
    ax.axis('off')
plt.suptitle('Train Augmentation — 8 samples from same image', fontsize=12)
plt.tight_layout()
plt.savefig('fig_aug_train.png', dpi=120, bbox_inches='tight')
plt.show()

"""### 8.5 Mosaic — Input Images"""

def create_mosaic(images, target_size=(512,512)):
    H, W = target_size
    canvas = Image.new('RGB',(W,H),(114,114,114))
    cx = np.random.randint(W//4, 3*W//4)
    cy = np.random.randint(H//4, 3*H//4)
    for img,(x1,y1,x2,y2) in zip(images,
        [(0,0,cx,cy),(cx,0,W,cy),(0,cy,cx,H),(cx,cy,W,H)]):
        canvas.paste(img.resize((x2-x1,y2-y1),Image.BILINEAR),(x1,y1))
    return canvas

if IMG_DIR.exists():
    sample_imgs = [Image.open(p).convert('RGB') for p in list(IMG_DIR.glob('*.jpg'))[10:14]]
else:
    clrs = [(200,80,80),(80,180,80),(80,80,200),(200,180,50)]
    sample_imgs = [
        Image.fromarray((np.full((375,500,3),c,dtype=np.uint8)
                         + np.random.randint(0,30,(375,500,3),dtype=np.uint8)).clip(0,255).astype(np.uint8))
        for c in clrs]

mosaic = create_mosaic(sample_imgs)

fig, axes = plt.subplots(1, 4, figsize=(14, 4))
for i,(ax,img) in enumerate(zip(axes,sample_imgs)):
    ax.imshow(img); ax.set_title(f'Input {i+1}'); ax.axis('off')
plt.suptitle('Mosaic Augmentation — Input Images', fontsize=12)
plt.tight_layout()
plt.savefig('fig_mosaic_inputs.png', dpi=120, bbox_inches='tight')
plt.show()

"""### 8.6 Mosaic — Output"""

fig, ax = plt.subplots(figsize=(6, 6))
ax.imshow(mosaic); ax.axis('off')
ax.set_title('Mosaic Output (512x512)', fontsize=12)
plt.tight_layout()
plt.savefig('fig_mosaic_output.png', dpi=120, bbox_inches='tight')
plt.show()

"""### 8.7 PyTorch Dataset Class"""

import albumentations as A
from albumentations.pytorch import ToTensorV2
import cv2
import torch
from pathlib import Path
import xml.etree.ElementTree as ET
from torch.utils.data import Dataset

import torch
from torch.utils.data import Dataset, DataLoader

train_transform_alb = A.Compose([
    A.RandomResizedCrop(size=(512, 512), scale=(0.5, 1.0), p=1.0),
    A.HorizontalFlip(p=0.5),
    A.ColorJitter(brightness=0.3, contrast=0.3, saturation=0.3, hue=0.1, p=0.8),
    A.ToGray(p=0.05),
    A.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
    ToTensorV2(),
], bbox_params=A.BboxParams(format='pascal_voc', label_fields=['class_labels']))

val_transform_alb = A.Compose([
    A.Resize(height=512, width=512),
    A.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
    ToTensorV2(),
], bbox_params=A.BboxParams(format='pascal_voc', label_fields=['class_labels']))

class VOC2012Dataset(Dataset):
    def __init__(self, root, split='trainval', transform=None, remove_difficult=True):
        self.root = Path(root)
        self.transform = transform
        self.remove_difficult = remove_difficult
        split_file = self.root / 'ImageSets' / 'Main' / f'{split}.txt'
        with open(split_file) as f:
            self.img_ids = [l.strip() for l in f if l.strip()]

    def __len__(self):
        return len(self.img_ids)

    def __getitem__(self, idx):
        img_id = self.img_ids[idx]
        img_path = str(self.root / 'JPEGImages' / f'{img_id}.jpg')
        image = cv2.imread(img_path)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        tree = ET.parse(self.root / 'Annotations' / f'{img_id}.xml')
        root = tree.getroot()
        W = int(root.find('size/width').text)
        H = int(root.find('size/height').text)

        bboxes = []
        class_labels = []

        for obj in root.findall('object'):
            if self.remove_difficult and int(obj.findtext('difficult') or 0): continue
            name = obj.findtext('name')
            bb = obj.find('bndbox')
            xmin = max(0, float(bb.findtext('xmin')))
            ymin = max(0, float(bb.findtext('ymin')))
            xmax = min(W, float(bb.findtext('xmax')))
            ymax = min(H, float(bb.findtext('ymax')))

            if xmax > xmin and ymax > ymin:
                bboxes.append([xmin, ymin, xmax, ymax])
                class_labels.append(CLASS_TO_IDX.get(name, -1))

        if self.transform:
            augmented = self.transform(image=image, bboxes=bboxes, class_labels=class_labels)
            image = augmented['image']
            bboxes = augmented['bboxes']
            class_labels = augmented['class_labels']

        target = {
            'boxes': torch.as_tensor(bboxes, dtype=torch.float32),
            'labels': torch.as_tensor(class_labels, dtype=torch.int64),
            'img_id': img_id,
            'orig_size': torch.tensor([H, W])
        }
        return image, target


def voc_collate_fn(batch):
    images, targets = zip(*batch)
    return torch.stack(images, 0), list(targets)


print('VOC2012Dataset ready.')
print('''
Usage:
    ds     = VOC2012Dataset('./VOCdevkit/VOC2012', split='train', transform=train_transform)
    loader = DataLoader(ds, batch_size=16, shuffle=True,
                        num_workers=4, collate_fn=voc_collate_fn, pin_memory=True)
''')

# Thử nghiệm visualize 1 sample sau khi augment để chắc chắn box đã đi theo ảnh
ds_check = VOC2012Dataset(VOC_ROOT, split='train', transform=train_transform_alb)
img_t, target_t = ds_check[0]

def show_fixed_sample(img_tensor, boxes):
    img = unnorm(img_tensor)
    plt.figure(figsize=(6,6))
    plt.imshow(img)
    for box in boxes:
        x1, y1, x2, y2 = box
        plt.gca().add_patch(plt.Rectangle((x1, y1), x2-x1, y2-y1, fill=False, color='red', lw=2))
    plt.title("Augmented Image with Corrected Bboxes")
    plt.show()

show_fixed_sample(img_t, target_t['boxes'])

"""### 8.8 Class Weights for Imbalance"""

import torch

cc   = df_clean['class'].value_counts()
tot  = cc.sum()
n    = len(cc)
wts  = {c: tot/(n*v) for c,v in cc.items()}
w_vals = [wts.get(c,1.0) for c in VOC_CLASSES]
weight_tensor = torch.tensor(w_vals, dtype=torch.float32)

fig, ax = plt.subplots(figsize=(13, 5))
colors = ['#e74c3c' if w > 2 else '#4C72B0' for w in w_vals]
ax.bar(VOC_CLASSES, w_vals, color=colors, edgecolor='none')
ax.axhline(1.0, color='gray', ls='--', lw=1.2, label='Weight = 1.0 (balanced)')
ax.set_xticklabels(VOC_CLASSES, rotation=40, ha='right')
ax.set_ylabel('Class Weight')
ax.set_title('Inverse-Frequency Class Weights  (for CrossEntropyLoss)')
for i,(w) in enumerate(w_vals):
    ax.text(i, w+0.02, f'{w:.2f}', ha='center', va='bottom', fontsize=7)
ax.legend(); ax.grid(axis='y')
plt.tight_layout()
plt.savefig('fig_class_weights.png', dpi=120, bbox_inches='tight')
plt.show()

print('Usage:  criterion = nn.CrossEntropyLoss(weight=weight_tensor.to(device))')

"""## Step 9 — Pipeline Summary"""

print('''
=================================================================
     PASCAL VOC 2012 — PREPROCESSING PIPELINE SUMMARY
=================================================================
  1. LOADING
     [x] Parse XML -> DataFrame
     [x] Read train.txt / val.txt / trainval.txt

  2. CLEANING
     [x] Remove difficult=1 objects
     [x] Validate bbox (xmin<xmax, ymin<ymax, w>0, h>0)
     [x] Clip bboxes to image boundary

  3. NORMALIZATION
     [x] [0,255] -> [0.0, 1.0]  via ToTensor
     [x] mean=(0.485, 0.456, 0.406)
         std =(0.229, 0.224, 0.225)

  4. RESIZING (choose based on model)
     SSD-300      -> 300x300
     SSD-512      -> 512x512
     Faster RCNN  -> min=800, max=1333 (letterbox)
     YOLOv5/v8   -> 640x640 (letterbox)

  5. AUGMENTATION (train only)
     [x] RandomHorizontalFlip (p=0.5)
     [x] ColorJitter
     [x] RandomResizedCrop (scale 0.5-1.0)
     [x] RandomErasing (p=0.1)
     [x] Mosaic (4-image, YOLOv4+)
     [x] MixUp (lambda ~ Beta(0.2, 0.2))

  6. CLASS IMBALANCE
     [x] Inverse-frequency class weights
     [x] Focal Loss (alpha=0.25, gamma=2.0)

  7. DATALOADER
     [x] VOC2012Dataset + voc_collate_fn
     [x] pin_memory=True, num_workers>=4
=================================================================
''')
vc = df['class'].value_counts()
print(f'Imbalance ratio : {vc.max()/vc.min():.0f}x')
print(f'person share    : {vc["person"]/len(df)*100:.1f}%')

!pip install ultralytics -q

import yaml

# Định nghĩa cấu hình YOLOv8 Nano cho 20 lớp
# Chúng ta chỉ cần chỉ định số lượng lớp (nc), Ultralytics sẽ lo phần kiến trúc mặc định
yolo_config = {
    'nc': len(VOC_CLASSES),
    'names': {i: name for i, name in enumerate(VOC_CLASSES)}
}

with open('yolov8n.yaml', 'w') as f:
    yaml.dump(yolo_config, f)

print("Đã tạo file yolov8n.yaml thành công với nc=20.")
# Kiểm tra nội dung file
!cat yolov8n.yaml

from ultralytics import YOLO
from ultralytics.utils.loss import v8DetectionLoss
from types import SimpleNamespace

def prepare_yolo_targets(batch_targets, device, target_size=(512, 512)):
    yolo_targets = []
    for i, target in enumerate(batch_targets):
        boxes = target['boxes']
        labels = target['labels']
        orig_h, orig_w = target['orig_size']
        if len(boxes) == 0: continue
        bw = (boxes[:, 2] - boxes[:, 0]) / orig_w
        bh = (boxes[:, 3] - boxes[:, 1]) / orig_h
        cx = (boxes[:, 0] + boxes[:, 2]) / (2 * orig_w)
        cy = (boxes[:, 1] + boxes[:, 3]) / (2 * orig_h)
        batch_idx = torch.full((len(labels), 1), i)
        target_tensor = torch.cat([batch_idx, labels.unsqueeze(1).float(), cx.unsqueeze(1), cy.unsqueeze(1), bw.unsqueeze(1), bh.unsqueeze(1)], dim=1)
        yolo_targets.append(target_tensor)
    return torch.cat(yolo_targets, dim=0).to(device) if yolo_targets else torch.zeros((0, 6)).to(device)

# Sửa lại hàm train để sử dụng đúng transform của Albumentations và hiển thị summary
def train_yolo_baseline(epochs=3, batch_size=16, lr=1e-3):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    # Sử dụng Albumentations transform
    train_ds = VOC2012Dataset(VOC_ROOT, split='train', transform=train_transform_alb)
    train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True, num_workers=2, collate_fn=voc_collate_fn)

    # Load model với config 20 classes
    model = YOLO('yolov8n.yaml')
    model.load('yolov8n.pt')

    net = model.model.to(device)

    # Hiển thị thông tin tóm tắt model
    print("\n" + "="*30)
    print(f"MODEL SUMMARY")
    # SỬA LỖI: Truy cập số lượng lớp từ biến VOC_CLASSES thay vì net.nc
    print(f"Classes (nc): {len(VOC_CLASSES)}")
    print(f"Parameters: {sum(p.numel() for p in net.parameters()):,}")
    print("="*30 + "\n")

    for param in net.parameters():
        param.requires_grad = True

    criterion = v8DetectionLoss(net)
    criterion.hyp = SimpleNamespace(box=7.5, cls=0.5, dfl=1.5)
    criterion.nc = len(VOC_CLASSES)
    optimizer = torch.optim.AdamW(net.parameters(), lr=lr, weight_decay=1e-4)

    for epoch in range(epochs):
        net.train()
        pbar = tqdm(train_loader, desc=f'Epoch {epoch+1}/{epochs}')
        for images, targets in pbar:
            images = images.to(device)
            yolo_targets = prepare_yolo_targets(targets, device)
            batch_dict = {'batch_idx': yolo_targets[:, 0], 'cls': yolo_targets[:, 1], 'bboxes': yolo_targets[:, 2:]}

            optimizer.zero_grad()
            preds = net(images)
            loss, _ = criterion(preds, batch_dict)

            scalar_loss = loss.sum() if loss.dim() > 0 else loss

            if scalar_loss.grad_fn is not None:
                scalar_loss.backward()
                optimizer.step()

            pbar.set_postfix({'loss': f'{scalar_loss.item():.3f}'})
        torch.save(net.state_dict(), f'yolov8_voc_fixed_epoch_{epoch+1}.pt')

# Chạy training
train_yolo_baseline(epochs=5, batch_size=16, lr=1e-3)

import matplotlib.pyplot as plt

def evaluate_yolo(net, val_loader, device):
    net.eval()
    total_val_loss = 0
    criterion = v8DetectionLoss(net)
    criterion.hyp = SimpleNamespace(box=7.5, cls=0.5, dfl=1.5)
    criterion.nc = len(VOC_CLASSES)

    print("\nRunning Evaluation...")
    with torch.no_grad():
        for images, targets in tqdm(val_loader, desc="Evaluating"):
            images = images.to(device)
            yolo_targets = prepare_yolo_targets(targets, device)
            batch_dict = {'batch_idx': yolo_targets[:, 0], 'cls': yolo_targets[:, 1], 'bboxes': yolo_targets[:, 2:]}

            preds = net(images)
            loss, _ = criterion(preds, batch_dict)
            scalar_loss = loss.sum() if loss.dim() > 0 else loss
            total_val_loss += scalar_loss.item()

    avg_val_loss = total_val_loss / len(val_loader)
    return avg_val_loss

# Khởi tạo lại dataset và loader cho Validation
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
val_ds = VOC2012Dataset(VOC_ROOT, split='val', transform=val_transform)
val_loader = DataLoader(val_ds, batch_size=16, shuffle=False, num_workers=2, collate_fn=voc_collate_fn)

# SỬA LỖI: Load model test với config nc=20
model_test = YOLO('yolov8n.yaml')
model_test.load('yolov8n.pt')
net_test = model_test.model.to(device)

# Load weights (thay đổi file name nếu cần)
try:
    state_dict = torch.load('yolov8_voc_fixed_epoch_1.pt')
    net_test.load_state_dict(state_dict)
    val_loss = evaluate_yolo(net_test, val_loader, device)
    print(f"Validation Loss: {val_loss:.4f}")
except FileNotFoundError:
    print("Chưa tìm thấy file weight. Hãy đảm bảo bạn đã chạy cell train trước đó.")

import torch
import numpy as np
from tqdm import tqdm
from ultralytics.utils.metrics import DetMetrics, box_iou
from ultralytics.utils.nms import non_max_suppression
from ultralytics.utils.ops import scale_boxes

def get_tp_matrix(pd_boxes, pd_cls, gt_boxes, gt_cls, iouv):
    """Tính toán matrix True Positive dựa trên IoU và class."""
    tp = torch.zeros(pd_boxes.shape[0], iouv.shape[0], dtype=torch.bool, device=pd_boxes.device)
    if gt_boxes.shape[0] == 0:
        return tp

    iou = box_iou(gt_boxes, pd_boxes)
    for j, step in enumerate(iouv):
        matches = (iou >= step) & (gt_cls[:, None] == pd_cls[None, :])
        if matches.any():
            for pd_idx in range(pd_boxes.shape[0]):
                gt_indices = matches[:, pd_idx].nonzero(as_tuple=False)
                if len(gt_indices) > 0:
                    best_match = gt_indices[iou[gt_indices, pd_idx].argmax()]
                    tp[pd_idx, j] = True
                    matches[best_match, :] = False
    return tp

def evaluate_map(net, val_loader, device, names, iou_thres=0.5, conf_thres=0.001):
    net.eval()
    metrics = DetMetrics(names=names)
    iouv = torch.linspace(0.5, 0.95, 10).to(device)
    stats_added = False

    for images, targets in tqdm(val_loader, desc="Evaluating"):
        images = images.to(device)
        with torch.no_grad():
            preds = net(images)
        processed_preds = non_max_suppression(preds, conf_thres, iou_thres)

        for i, p in enumerate(processed_preds):
            target = targets[i]
            gt_boxes = target['boxes'].to(device)
            gt_cls = target['labels'].to(device)

            if len(p) == 0:
                if len(gt_cls) > 0:
                    metrics.stats['tp'].append(np.zeros((0, 10), dtype=bool))
                    metrics.stats['conf'].append(np.zeros(0))
                    metrics.stats['pred_cls'].append(np.zeros(0))
                    metrics.stats['target_cls'].append(gt_cls.cpu().numpy())
                    stats_added = True
                continue

            p_boxes = p[:, :4].clone()
            orig_img_size = target['orig_size'].cpu().tolist()
            p_boxes = scale_boxes((512, 512), p_boxes, orig_img_size)

            tp = get_tp_matrix(p_boxes, p[:, 5], gt_boxes, gt_cls, iouv)

            metrics.stats['tp'].append(tp.cpu().numpy())
            metrics.stats['conf'].append(p[:, 4].cpu().numpy())
            metrics.stats['pred_cls'].append(p[:, 5].cpu().numpy())
            metrics.stats['target_cls'].append(gt_cls.cpu().numpy())
            stats_added = True

    if not stats_added:
        print("Warning: No samples were added to metrics. Check conf_thres or data loading.")
        return {}

    metrics.process()
    results = metrics.results_dict()

    map50 = results.get('metrics/mAP50(B)', 0)
    print(f"\nmAP50: {map50:.4f}")
    return results

voc_names = {i: name for i, name in enumerate(VOC_CLASSES)}
map_results = evaluate_map(net_test, val_loader, device, names=voc_names)